# Travis CI (MIT License) configuration file for the Underscores WordPress theme.
# @link https://travis-ci.org/

# For use with the WPTrek WordPress theme.
# @link https://github.com/GiovanniRiefolo/WPTrek

# Tell Travis CI which OS and which distro to use.
os: linux
dist: xenial

# Cache directories between builds.
# @link https://docs.travis-ci.com/user/caching/#arbitrary-directories
cache:
  directories:
    # Cache directory for npm.
    - $HOME/.npm
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

# Declare project language.
# @link https://docs.travis-ci.com/user/languages/php/
language:
  - php
  - javascript

php:
  - 7.3
  - 7.4

jobs:
  fast_finish: true

before_install:
  # Speed up build time by disabling Xdebug.
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
  # Download and install the latest long-term support release of node.
  - if [[ "$SNIFF" == 1 ]]; then nvm install --lts; fi
  # Install Composer dependencies.
  - composer install
  # Install NPM dependencies.
  - if [[ "$SNIFF" == 1 ]]; then npm install; fi

script:
  # Validate the composer.json file.
  # @link https://getcomposer.org/doc/03-cli.md#validate
  - composer validate --no-check-all --strict

# Receive notifications for build results.
# @link https://docs.travis-ci.com/user/notifications/#configuring-email-notifications
notifications:
  email: false